version: "3.9"

services:
  db:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"

  app:
    image: webdevops/php-apache:8.2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    working_dir: /app
    expose:
      - '80'
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      WEB_DOCUMENT_ROOT: /app/public
    labels:
      - traefik.http.services.laravel-demo-laravel-jgrsdw-2-web.loadbalancer.server.port=80
      - traefik.http.routers.laravel-demo-laravel-jgrsdw-2-websecure.loadbalancer.server.port=80
      - traefik.http.routers.laravel-demo-laravel-jgrsdw-2-websecure.service=laravel-demo-laravel-jgrsdw-2-websecure
      - traefik.http.routers.laravel-demo-laravel-jgrsdw-2-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
    command: >-
      bash -c "composer install --no-dev --optimize-autoloader \
      && php artisan config:cache \
      && php artisan route:cache \
      && php artisan view:cache \
      && supervisord -n"

volumes:
  db-data: 