version: "3.9"

services:
  db:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - dokploy-network

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - dokploy-network

  app:
    image: webdevops/php-apache:8.2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    working_dir: /app
    expose:
      - '80'
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      DB_CONNECTION: mysql
      WEB_DOCUMENT_ROOT: /app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`demo.olivierflentge.nl`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"
    command: >-
      bash -c "composer install --no-dev --optimize-autoloader \
      && chown -R application:application storage bootstrap/cache \
      && chmod -R ug+rwX storage bootstrap/cache \
      && supervisord -n"
    networks:
      - dokploy-network

volumes:
  db-data:

networks:
  dokploy-network:
    external: true 